### ISSUE TITLE
Reactive SVG

### ISSUE THREAD

**Issue by eizenberg** [bobtail-dev/bobtail#14]
Thanks for updating the lag-bind implementations earlier. Really useful.

I've added a bar chart to my app. I wanted it to be reactive to my model, but also wanted to use SVG for the graphics. An hour of hacking resulted in rxv, a port of rxt for svg:
https://gist.github.com/eizenberg/6620722

Obviously it's incomplete, but it works quite well.
Anyway I'm not sure it's part of your roadmap, so please let me know what would be the best way to maintain this code.

**Comment by yang** [comment]
Hot.  I'll play with this—what does the user code look like (e.g. your bar plot)?

**Comment by eizenberg** [comment]
Cool. I'll set up a live example for you to play with later this week.

**Comment by deanrad** [comment]
@eizenberg - have you got any farther on reactive svg ?

**Comment by eizenberg** [comment]
@chicagogrooves Didn't get to it unfortunately. It's been a busy few months. 

Feel free to close this...

**Comment by yavorsky** [comment]
@eizenberg Cool! I used reactive-coffee with d3 and will offer solutions I used. Also, we need to be careful when calling `rxv.importTags`, because it's adding many useful variable names to the scope like `path` or `image`..

**Comment by drernie** [comment]
I'm also looking at use SVG with reactive-coffee.  Should I revive @eizenberg's implementation? @aqson, did you post your d3 examples anywhere?

**Comment by drernie** [comment]
@yang Any update?  Would it help to increase the bounty? :-)

**Comment by drernie** [comment]
@yang I have updated  @eizenberg's implementation to https://gist.github.com/drernie/f27c92c9e78ed80545e2 and tested it at http://jsfiddle.net/DrErnie/p09bjgh3/.  Any chance you can integrate it into the main branch?  

Would it help if I forked and created a pull request?

**Comment by yang** [comment]
Sick!!  Sorry for the delay, Ernie—I've been hosed with work lately.  But
really glad you got something working here!  Yes, please go ahead and
create a pull request.  I'm also happy to fill in other stuff around this
including documentation.

**Comment by drernie** [comment]
Just submitted the fix as pull request #57.  This is my first pull request, so let me know if I missed anything.  Any idea when this might show up on a CDN so I can use it directly?

Thanks!

**Comment by drernie** [comment]
FYI, a potentially serious issue.  When testing this with real code, I've discovered that it generated the SVG tags just fine, and they show up in the DOM, but the page doesn't display the graphics.

http://jsfiddle.net/DrErnie/nn898h00/

Any suggestions for why my streamlined version is working differently than the original patch?!?

**Comment by yang** [comment]
Awesome, thanks for taking a stab @drernie—will take a look.

**Comment by drernie** [comment]
Ah, I figured out that the original patch used:

```
elt = document.createElementNS('http://www.w3.org/2000/svg', tag)
```

That returns an SVGElement.  I added that to my pacth, and it renders properly. Yeah!

But, the current version of reactive-coffee creates elements with:

$('<#{tag}/>')

Which returns -- not an HTMLElement -- but an Object where the Element is item "0".   I'm still trying to figure out how to wrap an SVG Element to look the same..

**Comment by drernie** [comment]
Okay, I think I've figured out what's going on.  I didn't realize that '$' is the same as "JQuery", and that if you pass it a _string_ instead of an element or selector it actually creates "innerHTML".   

http://api.jquery.com/jQuery/

This is explicitly HTML, though, which is why it doesn't work for SVG.  Fortunately, there are alternative ways to do the equivalent for an "innerSVG":

http://stackoverflow.com/questions/9723422/is-there-some-innerhtml-replacement-in-svg-xml

See also: https://code.google.com/p/innersvg/source/browse/innersvg.js

However, they all seem to have some downsides.  Any thoughts on which approach would work best for reactive-coffee's needs? Or should I just brute force something with createElementNS?

**Comment by yang** [comment]
Just in case my comment on the PR thread slipped through—it's certainly fine to bypass jQuery, but alternatively you can pull in jQuery.SVG if you want a more jQuery interface.  I think either way would work.  I'm a fan of getting your (very promising!) work merged in and iterating from there to make things better/nicer.

**Comment by drernie** [comment]
Hi Yang,

> On Oct 21, 2014, at 11:35 PM, Yang Zhang notifications@github.com wrote:
> Just in case my comment on the PR thread slipped through—it's certainly fine to bypass jQuery, but alternatively you can pull in jQuery.SVG if you want a more jQuery interface. I think either way would work. I'm a fan of getting your (very promising!) work merged in and iterating from there to make things better/nicer.
> 
> Thanks! I’m heads down getting my alpha out the door, but keep tweaking the patch. I notice you’re local. May we can meet for a beer some afternoon and hammer it all out!

— Erne P.

**Comment by yang** [comment]
Of course, no rush/pressure at all!  I am indeed local—I'm down for
beer/hack-session etc.
