### ISSUE TITLE
Enhancement: Dictionary syntax option

### ISSUE THREAD

**Issue by m1sta** [bobtail-dev/bobtail#5]
We are currently are stuck with closing brackets when using multiline arrays in Coffeescript. In recognition of this limitation, I'd love to see reactive.coffee supporting an optional 'dictionary' syntax. Such an alternative would cause the todo example updated to look like this...

``` coffeescript
# This is our core data model, an array of Task objects.

class Task
    constructor: (descrip, priority, isDone) ->
        @descrip = rx.cell(descrip)
        @priority = rx.cell(priority)
        @isDone = rx.cell(isDone)

tasks = rx.array fromDictionary
    0: new Task('Get milk', 'important', false)
    1: new Task('Play with Reactive Coffee', 'critical', false)
    2: new Task('Walk the dog', 'meh', false)

currentTask = rx.cell(tasks.at(0)) # "View model" of currently selected task

# Our main view: a checklist of tasks, a button to add a new task, and a task
# editor component (defined further down).
taskList = div
    class: 'task-manager'
    contents:
        count: h1 contents: bind -> "#{tasks.length()} task(s) for today"
        list: ul
            class: 'tasks'
            contents: tasks.map (task) -> item: li
                class: bind -> "task-#{if task == currentTask.get() then 'selected' else 'unselected'}"
                contents:
                    checkbox: input type: 'checkbox', click: -> task.isDone.set(@is(':checked'))
                    desc: span class:'descrip', contents: bind -> "#{task.descrip.get()} (#{task.priority.get()})"
                    edit: a href: 'javascript: void 0', click: (-> currentTask.set(task)), contents: 'Edit'
        newTaskButton: button click: (-> tasks.push(new Task('Task', 'none', false))), contents: 'Add new task'
        taskEditor: taskEditor
            task: bind -> currentTask.get()
            onSubmit: (descrip, priority) ->
                currentTask.get().descrip.set(descrip)
                currentTask.get().priority.set(priority)

# The task editor demonstrates how to define a simple component.
taskEditor = (options) ->
    task = -> options.task.get()
    theForm = form
        contents:
            heading: h2 contents: 'Edit Task'
            description: div contents:
                label: label contents: 'Description'
                detail: input type: 'text', value: bind -> task().descrip.get()
                br1: br {}
            priority: div contents:
                label: label contents: 'Priority'
                detail: input type: 'text', value: bind -> task().priority.get()
                br2: br {}
            status: div contents:
                label: label contents: 'Status'
                detail: span contents: bind -> [if task().isDone.get() then 'Done' else 'Not done']
                br3: br {}
            updateButton: button contents: 'Update'
        onsubmit: ->
            options.onSubmit(this.contents.description.val().trim(), this.contents.priority.val().trim())
            @reset()
            false

$ -> $('body').append taskList
```

A little tweaking could make the 'bind' keyword unnecessary as a regular suffix to the 'contents' attribute.

**Comment by yang** [comment]
Oh, very interesting. But how would you maintain element ordering?

**Comment by m1sta** [comment]
From my experience the order of the keys in the dictionary will be as per their order when the dictionary was created, as long as the keys are not numbers.  I'm not sure what the specification states on this though. It might just be luck.

eg.

```
var example = {c:1,b:2,a:2,z:1,x:0}
for(var key in example) console.log(key)
```

When I started playing with this I actually used numbered keys with the key name notifying the sequence. Later I decided what was proposed above was better given the key ordering.

**Comment by m1sta** [comment]
Just checked the specification and then the actual behaviour of the major browsers. In theory the keys are unordered but what I've stated above seems to hold true for _at least_ Internet Explorer 6+, Chrome, and Firefox.

**Comment by yang** [comment]
There was also another similar suggestion brought up that would get rid of the square brackets:

```
div {class: 'profile'},
  img {src: '...'}
  div ...
  input {type: 'text', value: '...'}
```

This avoids needing everything to be named and jQuery objects to be munged.

We'll try adding this alternative syntax, not to the core but as an extension, such that users can opt-in to a dialect of their choosing. The core will probably see some refactoring so that users can more easily introduce their own preferred dialects (which we'll be happy to merge).

**Comment by m1sta** [comment]
I like this syntax too.  I can definitely imagine using it. 

The naming of things is something I find helpful from a readability perspective (and for element selection if they are transposed into ids) but most of all I think the original proposal excels when you assume that the attributes of an element are a little more complex (ie. interaction events, selective contents and classes). It probably comes down to preferences for inlining functions in templates or not. I personally like inlining functions in my template (in this situation) since we're already writing code here. Given the way the current todo example is written I assumed that you like it too.

In any case it's really just a question of verbosity. I'd prefer not to need a sneaky comma, like so...

``` coffeescript
div
 class: 'test'
 onClick: (()-> ),
 div a
 div b

div 
  class:'test'
  onclick: 
     action a
  ,
  div a
  div b
```

... but I also don't think it's a major issue. In any case it's an improvement on the current array based syntax.

Having the three syntax options (current array based, single object based as proposed in this issue, and arguments based like noted in the comment above) might all be able to be supported by default. Perhaps I'm missing something but...

``` coffeescript
if arguments.length is 1  #object based
    elementAttributes = arguments[0]
    elementList = if elementAttributes.contents then (element for id, element of elementAttributes.contents) else []
    delete elementAttributes.contents

else if arguments[1] instanceof Array #array based (existing)
     elementAttributes = arguments[0]
     elementList = arguments[1]

else #arguments based
     elementAttributes = arguments[0]
     elementList = arguments.slice(1)
```

**Comment by m1sta** [comment]
Further to my note that 'A little tweaking could make the 'bind' keyword unnecessary as a regular suffix to the 'contents' attribute' I think it would be neat if reactive could detect if a parameter was a reactive element generating function (ie. the 'br' function), and if it were, would automatically execute the function.

The value here would be that you could write the following...

``` coffeescript
div contents:
   header: div contents: "Hello", class: "title"
   separator: br
   subtitle: div contents: "World", class: "subtitle"

#or

div {},
   div class: "title", "Hello"
   br
   div class: "subtitle", "World"

```

I actually kind of like this last one.

**Comment by yang** [comment]
"jQuery objects being munged" is referring to if you literally meant:

```
this.contents.description.val()
```

`this.contents.description` is accessing children by keys, and then the jQuery `val` method is called on the last element.  Namespace conflicts are likely to happen; in fact, `this.contents` already clashes with http://api.jquery.com/contents/.  (That's my take - let me know if you had something else in mind.)

You're right in that the `contents:` syntax is more scalable though.  The `br` auto-invocation seems like a nice idea.

We'll build out some of these dialects/syntax changes - thanks for the feedback!

**Comment by m1sta** [comment]
Ah ok. Hadn't thought about that. I was assuming that 'this' would be a custom object based off the tree.

Assuming it _was_ a custom object the syntax should probably be more like `this.contents.description.$.val()` to prevent confusion.
If 'this' was a native jQuery object then I'd probably expect to use something like `$.find()` instead.

**Comment by deanrad** [comment]
I also thought about the issue of closing tags, and thought perhaps this style was the way to go:

table "#posts-table", ->
    tr ->
      th 'Title'
      th 'Content'

(From https://github.com/goodeggs/teacup-rails#usage)

I've made a pull request for some of these features, but I'm still using closing array tags at the moment, where I think teacup does successive appends instead of returning the last item evaluated in the function.
