### ISSUE TITLE
Proposal: deprecate and eventually remove rxt.importTags

### ISSUE THREAD

**Issue by rmehlinger** [bobtail-dev/bobtail#60]
So, rxt.importTags is a potentially very scary function. Importing several dozen methods into a top level namespace is inherently very risky, and code written this way will be less maintainable. Instead, tags should be referenced as part of an explicit namespace, e.g., Tags.div, Tags.a, etc. As such, I think we should deprecate this function, and remove it as part of the next major release.

**Comment by yang** [comment]
I concur.  Let's make a pass over the website/docs to replace all uses of global tags with qualified names (using the "R" prefix to keep it as painlessly little additional typing as possible).  We can leave it around in the API docs as a utility "if you really need it" for the time being.
