### ISSUE TITLE
new $.rx property: 'enabled'

### ISSUE THREAD

**Issue by rmehlinger** [bobtail-dev/bobtail#61]
Or 'disabled'.

Example, where $field is an input of some sort:
`R.div {class: bind-> 'disabled' if $field.rx('disabled')}, $field`

**Comment by yang** [comment]
The difficulty with arbitrary element properties like `disabled` is there are no native DOM listeners for these events as they are not user-triggered events (unlike clicking a checkbox or keypress in a text input).  For something like this, you would need to rely on something more advanced, like polling or [DOM Mutation Observers](http://addyosmani.com/blog/mutation-observers/) (and the dust hasn't settled on that, not to mention it being tricky in general with many corner cases).

I'm going to close this for now but let me know if you had other specific thoughts here or if what I'm saying doesn't make sense.
